### ISSUE TITLE
Maybe incorrect?

### ISSUE THREAD

**Issue by ioquatix** [zombocom/dead_end#151]
https://github.com/zombocom/dead_end/blob/d2d7648d4544d4198ad41e0009b0f0078b6ddb75/lib/dead_end/core_ext.rb#L53

cc @fxn

**Comment by schneems** [comment]
What’s wrong with it? Tests seem to pass. FWIW this is not a code path for Ruby 3.2.

**Comment by fxn** [comment]
Hey!

It's fine. There's indentation due to the `if/else`, but it is a top-level autoload for a top-level constant. 👍

**Comment by ioquatix** [comment]
Thanks for checking @fxn :)
