### ISSUE TITLE
Extend SyntaxError?

### ISSUE THREAD

**Issue by ioquatix** [zombocom/dead_end#153]
https://github.com/zombocom/dead_end/blob/47cdf69e5c932db0e0bdd3f1c4052e08768db501/lib/dead_end/pathname_from_message.rb#L15

I wonder if we should add the path you want directly to the syntax error instance? That would make more sense to me.

**Comment by schneems** [comment]
It’s talked about in https://bugs.ruby-lang.org/issues/18159.

**Comment by ioquatix** [comment]
Awesome!!
